# basic

In [1]:
%load_ext autoreload
%autoreload all

In [ ]:
import polars as pl
import numpy as np
import pickle
import itertools

import configs_mapped as configs_mapped
from src.tokenizer import GraphTokenizer
from src.iterative_selection import iterative_approach_w_graph_red, IterativeMarginalGainMax

# 0. load files

In [ ]:
with open(configs_mapped.ProcessedGraph().candidate_is_a_reachable_dict, "rb") as f:
    candidate_reachable_child_map = pickle.load(f)

df_concept_hug_w_depth = pl.read_parquet(configs_mapped.ProcessedGraph.concept_w_depth)
mapped_candidate_rel_dist_prop = (pl.read_parquet(configs_mapped.ProcessedGraph().mapped_candidate_rel_dist_prop)
                                  
                                  # remove all relations in subgraph where candidate and mapped are distant
                                  .filter(pl.col("distance") <= configs_mapped.TokenizerParam().max_dist_candidate)
                                  )

In [ ]:
pl.read_parquet(configs_mapped.ProcessedGraph.concept_w_depth)

shape: (447_420, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ label     ┆ concept_t ┆ sem_tag   ┆ … ┆ collectio ┆ is_mapped ┆ max_depth ┆ min_dept │
│ ---       ┆ ---       ┆ ype       ┆ ---       ┆   ┆ n         ┆ ---       ┆ ---       ┆ h        │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ bool      ┆ i64       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ list[str] ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 127265005 ┆ Neoplasm  ┆ SCT_PRE   ┆ disorder  ┆ … ┆ null      ┆ false     ┆ 10        ┆ 5        │
│           ┆ of        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ popliteal ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ lymph no… ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 273547007 ┆ Katz acti ┆ SCT_PRE   ┆ assessmen ┆ … ┆ null      ┆ false     ┆ 4         ┆ 4        │
│           ┆ vities of ┆           ┆ t scale   ┆   ┆           ┆           ┆           ┆          │
│           ┆ daily     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ livin…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 276134001 ┆ Second    ┆ SCT_PRE   ┆ attribute ┆ … ┆ null      ┆ false     ┆ 6         ┆ 6        │
│           ┆ value (at ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ tribute)  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 117033003 ┆ 117033003 ┆ SCT_POST  ┆ procedure ┆ … ┆ ["labo"]  ┆ true      ┆ 8         ┆ 7        │
│ :11668600 ┆ |Aerobic  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9=(168139 ┆ microbial ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001…      ┆ cu…       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 126932200 ┆ Insertion ┆ SCT_PRE   ┆ procedure ┆ … ┆ null      ┆ false     ┆ 7         ┆ 3        │
│ 6         ┆ of        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ denture   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ (procedur ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ …         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 41373000  ┆ Entire    ┆ SCT_PRE   ┆ body      ┆ … ┆ null      ┆ false     ┆ 16        ┆ 10       │
│           ┆ sacral    ┆           ┆ structure ┆   ┆           ┆           ┆           ┆          │
│           ┆ venous    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ plexus    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ (b…       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 332247009 ┆ Product   ┆ SCT_PRE   ┆ clinical  ┆ … ┆ null      ┆ false     ┆ 7         ┆ 6        │
│           ┆ containin ┆           ┆ drug      ┆   ┆           ┆           ┆           ┆          │
│           ┆ g         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ precisely ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 419495008 ┆ Percentag ┆ SCT_PRE   ┆ qualifier ┆ … ┆ null      ┆ false     ┆ 5         ┆ 5        │
│           ┆ e inhibit ┆           ┆ value     ┆   ┆           ┆           ┆           ┆          │
│           ┆ ion       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ (qualifi… ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 165289003 ┆ Memory:   ┆ SCT_PRE   ┆ finding   ┆ … ┆ null      ┆ false     ┆ 8         ┆ 8        │
│           ┆ present   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ year not  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ known…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 125144800 ┆ Polyclona ┆ SCT_PRE   ┆ disorder  ┆ … ┆ null      ┆ false     ┆ 10        ┆ 4        │
│ 3         ┆ l hypervi ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ scosity   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ synd…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# 1. iterative with graph reduction

In [ ]:
distance_score_types = ["sum", "tempered_sum"]
distance_type = ["inv", "inv_exp"]

for sc_type, d_type in itertools.product(distance_score_types, distance_type):
    candidate_rows = iterative_approach_w_graph_red(
        mapped_candidate_rel_dist_prop,
        candidate_reachable_child_map,
        sc_type,
        d_type,
    )
    pl.DataFrame(candidate_rows).write_parquet(f"{configs_mapped.IterativeGraphRed().path} {sc_type}_{d_type}.parquet")
    print(f"{sc_type} / {d_type}: {len(candidate_rows)} candidates selected")

number of candidates selected: 500, number of rows remaining: 417221
number of candidates selected: 1000, number of rows remaining: 329179
number of candidates selected: 1500, number of rows remaining: 288759
number of candidates selected: 2000, number of rows remaining: 273790
number of candidates selected: 2500, number of rows remaining: 273290
number of candidates selected: 3000, number of rows remaining: 272790
number of candidates selected: 3500, number of rows remaining: 272290
number of candidates selected: 4000, number of rows remaining: 271790
number of candidates selected: 4500, number of rows remaining: 271290
number of candidates selected: 5000, number of rows remaining: 270790
number of candidates selected: 5500, number of rows remaining: 270290
number of candidates selected: 6000, number of rows remaining: 269790
number of candidates selected: 6500, number of rows remaining: 269290
number of candidates selected: 7000, number of rows remaining: 268790
number of candidates selected: 7500, number of rows remaining: 268290
number of candidates selected: 8000, number of rows remaining: 259618
number of candidates selected: 8500, number of rows remaining: 256880
number of candidates selected: 9000, number of rows remaining: 231273
number of candidates selected: 9500, number of rows remaining: 209044
number of candidates selected: 10000, number of rows remaining: 193270
number of candidates selected: 10500, number of rows remaining: 171286
number of candidates selected: 11000, number of rows remaining: 161940
number of candidates selected: 11500, number of rows remaining: 141480
number of candidates selected: 12000, number of rows remaining: 140476
number of candidates selected: 12500, number of rows remaining: 139476
number of candidates selected: 13000, number of rows remaining: 126874
number of candidates selected: 13500, number of rows remaining: 110269
number of candidates selected: 14000, number of rows remaining: 97885
number of candidates selected: 14500, number of rows remaining: 97201
number of candidates selected: 15000, number of rows remaining: 96701
number of candidates selected: 15500, number of rows remaining: 96201
number of candidates selected: 16000, number of rows remaining: 95698
number of candidates selected: 16500, number of rows remaining: 95198
number of candidates selected: 17000, number of rows remaining: 94698
number of candidates selected: 17500, number of rows remaining: 94198
number of candidates selected: 18000, number of rows remaining: 91053
number of candidates selected: 18500, number of rows remaining: 83231
number of candidates selected: 19000, number of rows remaining: 73912
number of candidates selected: 19500, number of rows remaining: 65758
number of candidates selected: 20000, number of rows remaining: 58619
number of candidates selected: 20500, number of rows remaining: 54347
number of candidates selected: 21000, number of rows remaining: 48349
number of candidates selected: 21500, number of rows remaining: 41762
number of candidates selected: 22000, number of rows remaining: 40762
number of candidates selected: 22500, number of rows remaining: 39369
number of candidates selected: 23000, number of rows remaining: 34684
number of candidates selected: 23500, number of rows remaining: 29337
number of candidates selected: 24000, number of rows remaining: 25486
number of candidates selected: 24500, number of rows remaining: 24912
number of candidates selected: 25000, number of rows remaining: 24412
number of candidates selected: 25500, number of rows remaining: 23912
number of candidates selected: 26000, number of rows remaining: 23412
number of candidates selected: 26500, number of rows remaining: 22912
number of candidates selected: 27000, number of rows remaining: 21774
number of candidates selected: 27500, number of rows remaining: 19512
number of candidates selected: 28000, number of rows remaining: 16514
number of candidates selected: 28500, number of rows remaining: 14063
number of candidates selected: 29000, number of rows remaining: 11975
number of candidates selected: 29500, number of rows remaining: 10396
number of candidates selected: 30000, number of rows remaining: 8827
number of candidates selected: 30500, number of rows remaining: 7741
number of candidates selected: 31000, number of rows remaining: 6685
number of candidates selected: 31500, number of rows remaining: 5628
number of candidates selected: 32000, number of rows remaining: 4589
number of candidates selected: 32500, number of rows remaining: 4059
number of candidates selected: 33000, number of rows remaining: 3530
number of candidates selected: 33500, number of rows remaining: 3006
number of candidates selected: 34000, number of rows remaining: 2488
number of candidates selected: 34500, number of rows remaining: 1972
number of candidates selected: 35000, number of rows remaining: 1469
number of candidates selected: 35500, number of rows remaining: 964
number of candidates selected: 36000, number of rows remaining: 455
tempered_sum / inv_exp: 36453 candidates selected

# 2. marginal gain

In [ ]:
distance_types = ["inv", "inv_exp"]

max_candidate = mapped_candidate_rel_dist_prop["src.id"].n_unique()

for d_type in distance_types:
    margin_gain_iterative = IterativeMarginalGainMax(mapped_candidate_rel_dist_prop, d_type, max_candidates=max_candidate)
    selected_marginal_gain, _ = margin_gain_iterative.iterative_marginal_gain_greedy_without_k()
    selected_marginal_gain.write_parquet(f"{configs_mapped.IterativeMarginalGain().path}_{d_type}.parquet")

Marginal gain greedy: 1000it [01:35, 12.01it/s]

selected=1000, best_gain=7.9167, gain_ratio=0.0010, mean_state_score=0.4154

Marginal gain greedy: 2000it [02:54, 13.14it/s]

selected=2000, best_gain=3.2500, gain_ratio=0.0004, mean_state_score=0.4464

Marginal gain greedy: 3000it [04:07, 14.00it/s]

selected=3000, best_gain=2.0000, gain_ratio=0.0002, mean_state_score=0.4620

Marginal gain greedy: 4000it [05:27, 10.87it/s]

selected=4000, best_gain=1.5000, gain_ratio=0.0002, mean_state_score=0.4725

Marginal gain greedy: 5000it [06:46, 13.36it/s]

selected=5000, best_gain=1.1667, gain_ratio=0.0001, mean_state_score=0.4805

Marginal gain greedy: 6000it [07:55, 14.95it/s]

selected=6000, best_gain=1.0000, gain_ratio=0.0001, mean_state_score=0.4871

Marginal gain greedy: 7000it [09:06, 14.38it/s]

selected=7000, best_gain=0.8333, gain_ratio=0.0001, mean_state_score=0.4930

Marginal gain greedy: 8000it [10:14, 14.81it/s]

selected=8000, best_gain=0.7500, gain_ratio=0.0001, mean_state_score=0.4981

Marginal gain greedy: 9000it [11:18, 16.26it/s]

selected=9000, best_gain=0.7500, gain_ratio=0.0001, mean_state_score=0.5028

Marginal gain greedy: 10000it [12:20, 16.33it/s]

selected=10000, best_gain=0.6667, gain_ratio=0.0001, mean_state_score=0.5073

Marginal gain greedy: 11000it [13:21, 16.46it/s]

selected=11000, best_gain=0.6667, gain_ratio=0.0001, mean_state_score=0.5115

Marginal gain greedy: 12000it [14:23, 16.29it/s]

selected=12000, best_gain=0.6667, gain_ratio=0.0001, mean_state_score=0.5156

Marginal gain greedy: 13000it [15:28, 14.55it/s]

selected=13000, best_gain=0.6667, gain_ratio=0.0001, mean_state_score=0.5198

Marginal gain greedy: 14000it [16:34, 14.89it/s]

selected=14000, best_gain=0.6667, gain_ratio=0.0001, mean_state_score=0.5240

Marginal gain greedy: 15000it [17:40, 15.45it/s]

selected=15000, best_gain=0.6667, gain_ratio=0.0001, mean_state_score=0.5281

Marginal gain greedy: 16000it [18:44, 15.67it/s]

selected=16000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5319

Marginal gain greedy: 17000it [19:49, 14.95it/s]

selected=17000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5350

Marginal gain greedy: 18000it [20:57, 14.43it/s]

selected=18000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5382

Marginal gain greedy: 19000it [21:59, 16.28it/s]

selected=19000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5413

Marginal gain greedy: 20000it [23:00, 16.57it/s]

selected=20000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5444

Marginal gain greedy: 21000it [23:59, 16.39it/s]

selected=21000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5475

Marginal gain greedy: 22000it [24:59, 16.88it/s]

selected=22000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5507

Marginal gain greedy: 23000it [26:00, 16.68it/s]

selected=23000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5538

Marginal gain greedy: 24000it [27:04, 16.06it/s]

selected=24000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5569

Marginal gain greedy: 25000it [28:09, 16.01it/s]

selected=25000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5600

Marginal gain greedy: 26000it [29:09, 15.94it/s]

selected=26000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5632

Marginal gain greedy: 27000it [30:10, 16.85it/s]

selected=27000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5663

Marginal gain greedy: 28000it [31:06, 17.76it/s]

selected=28000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5694

Marginal gain greedy: 29000it [32:02, 17.58it/s]

selected=29000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5726

Marginal gain greedy: 30000it [32:58, 17.89it/s]

selected=30000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5757

Marginal gain greedy: 31000it [33:54, 18.23it/s]

selected=31000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5788

Marginal gain greedy: 32000it [34:49, 18.17it/s]

selected=32000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5819

Marginal gain greedy: 33000it [35:44, 18.27it/s]

selected=33000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5851

Marginal gain greedy: 34000it [36:39, 18.47it/s]

selected=34000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5882

Marginal gain greedy: 35000it [37:35, 18.07it/s]

selected=35000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5913

Marginal gain greedy: 36000it [38:33, 16.57it/s]

selected=36000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5944

Marginal gain greedy: 37000it [39:27, 18.33it/s]

selected=37000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.5976

Marginal gain greedy: 38000it [40:23, 17.30it/s]

selected=38000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.6007

Marginal gain greedy: 39000it [41:18, 17.09it/s]

selected=39000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.6038

Marginal gain greedy: 40000it [42:18, 17.20it/s]

selected=40000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.6069

Marginal gain greedy: 41000it [43:16, 17.45it/s]

selected=41000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.6101

Marginal gain greedy: 42000it [44:11, 18.19it/s]

selected=42000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.6132

Marginal gain greedy: 43000it [45:07, 18.71it/s]

selected=43000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.6163

Marginal gain greedy: 44000it [46:01, 17.98it/s]

selected=44000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.6195

Marginal gain greedy: 45000it [46:55, 18.99it/s]

selected=45000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.6226

Marginal gain greedy: 46000it [47:47, 20.07it/s]

selected=46000, best_gain=0.5000, gain_ratio=0.0001, mean_state_score=0.6257

Marginal gain greedy: 46150it [47:55, 16.05it/s]

Reached max_candidates=46150.

Marginal gain greedy: 1000it [01:34, 11.30it/s]

selected=1000, best_gain=6.8371, gain_ratio=0.0013, mean_state_score=0.2771

Marginal gain greedy: 2000it [02:50, 13.65it/s]

selected=2000, best_gain=3.2757, gain_ratio=0.0006, mean_state_score=0.3059

Marginal gain greedy: 3000it [04:01, 14.44it/s]

selected=3000, best_gain=2.1985, gain_ratio=0.0004, mean_state_score=0.3226

Marginal gain greedy: 4000it [05:15, 13.04it/s]

selected=4000, best_gain=1.6860, gain_ratio=0.0003, mean_state_score=0.3346

Marginal gain greedy: 5000it [06:27, 14.20it/s]

selected=5000, best_gain=1.3953, gain_ratio=0.0003, mean_state_score=0.3441

Marginal gain greedy: 6000it [07:39, 13.71it/s]

selected=6000, best_gain=1.1828, gain_ratio=0.0002, mean_state_score=0.3522

Marginal gain greedy: 7000it [08:48, 15.06it/s]

selected=7000, best_gain=1.0972, gain_ratio=0.0002, mean_state_score=0.3592

Marginal gain greedy: 8000it [09:56, 14.58it/s]

selected=8000, best_gain=0.9502, gain_ratio=0.0002, mean_state_score=0.3656

Marginal gain greedy: 9000it [11:01, 15.54it/s]

selected=9000, best_gain=0.9502, gain_ratio=0.0002, mean_state_score=0.3715

Marginal gain greedy: 10000it [12:04, 16.12it/s]

selected=10000, best_gain=0.8647, gain_ratio=0.0002, mean_state_score=0.3773

Marginal gain greedy: 11000it [13:03, 16.84it/s]

selected=11000, best_gain=0.8647, gain_ratio=0.0002, mean_state_score=0.3827

Marginal gain greedy: 12000it [14:04, 15.86it/s]

selected=12000, best_gain=0.8647, gain_ratio=0.0002, mean_state_score=0.3881

Marginal gain greedy: 13000it [15:05, 16.31it/s]

selected=13000, best_gain=0.8647, gain_ratio=0.0002, mean_state_score=0.3935

Marginal gain greedy: 14000it [16:05, 17.52it/s]

selected=14000, best_gain=0.8647, gain_ratio=0.0002, mean_state_score=0.3989

Marginal gain greedy: 15000it [17:02, 18.16it/s]

selected=15000, best_gain=0.7358, gain_ratio=0.0001, mean_state_score=0.4043

Marginal gain greedy: 16000it [18:01, 16.52it/s]

selected=16000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4084

Marginal gain greedy: 17000it [19:01, 16.48it/s]

selected=17000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4124

Marginal gain greedy: 18000it [19:59, 16.87it/s]

selected=18000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4163

Marginal gain greedy: 19000it [20:59, 16.69it/s]

selected=19000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4203

Marginal gain greedy: 20000it [22:03, 14.96it/s]

selected=20000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4242

Marginal gain greedy: 21000it [23:07, 16.30it/s]

selected=21000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4282

Marginal gain greedy: 22000it [24:06, 17.81it/s]

selected=22000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4321

Marginal gain greedy: 23000it [25:08, 16.67it/s]

selected=23000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4361

Marginal gain greedy: 24000it [26:06, 17.27it/s]

selected=24000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4401

Marginal gain greedy: 25000it [27:05, 17.12it/s]

selected=25000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4440

Marginal gain greedy: 26000it [28:04, 16.75it/s]

selected=26000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4480

Marginal gain greedy: 27000it [29:04, 16.88it/s]

selected=27000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4519

Marginal gain greedy: 28000it [30:05, 16.96it/s]

selected=28000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4559

Marginal gain greedy: 29000it [31:04, 17.09it/s]

selected=29000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4598

Marginal gain greedy: 30000it [31:59, 19.17it/s]

selected=30000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4638

Marginal gain greedy: 31000it [32:51, 19.11it/s]

selected=31000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4677

Marginal gain greedy: 32000it [33:44, 18.31it/s]

selected=32000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4717

Marginal gain greedy: 33000it [34:43, 16.27it/s]

selected=33000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4756

Marginal gain greedy: 34000it [35:40, 17.45it/s]

selected=34000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4796

Marginal gain greedy: 35000it [36:37, 17.92it/s]

selected=35000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4835

Marginal gain greedy: 36000it [37:33, 17.99it/s]

selected=36000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4875

Marginal gain greedy: 37000it [38:28, 18.10it/s]

selected=37000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4914

Marginal gain greedy: 38000it [39:23, 18.16it/s]

selected=38000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4954

Marginal gain greedy: 39000it [40:18, 18.32it/s]

selected=39000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.4993

Marginal gain greedy: 40000it [41:13, 18.15it/s]

selected=40000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.5033

Marginal gain greedy: 41000it [42:08, 18.19it/s]

selected=41000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.5072

Marginal gain greedy: 42000it [43:03, 18.19it/s]

selected=42000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.5112

Marginal gain greedy: 43000it [43:57, 18.68it/s]

selected=43000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.5152

Marginal gain greedy: 44000it [44:51, 18.69it/s]

selected=44000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.5191

Marginal gain greedy: 45000it [45:43, 19.15it/s]

selected=45000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.5231

Marginal gain greedy: 46000it [46:36, 19.05it/s]

selected=46000, best_gain=0.6321, gain_ratio=0.0001, mean_state_score=0.5270

Marginal gain greedy: 46150it [46:44, 16.46it/s]

Reached max_candidates=46150.

# tokenizer test (max dist  == 3)

In [ ]:
tokenizer = GraphTokenizer(df_concept_hug_w_depth,
                        mapped_candidate_rel_dist_prop,
                        candidate_reachable_child_map,
                        configs_mapped.TokenizerParam().max_dist_candidate
                        )

## tryout

In [6]:
# top 8000 candidates of highest degree
for k in np.arange(1000, 10000, 1000):
    example_candidates = mapped_candidate_rel_dist_prop.group_by("dst.id").agg(num_src = pl.col("src.id").n_unique()).sort(by = "num_src", descending=True).head(k)["dst.id"].to_list()
    scores, results, df_tok_all_n_dist = tokenizer.evaluate_components_and_tokenize(example_candidates, debug=True)

In [7]:
df_tok_all_n_dist# ["candidate_id"].n_unique()

shape: (205_398, 4)
┌────────────┬──────────────┬──────────┬──────────┐
│ mapped_id  ┆ candidate_id ┆ relation ┆ distance │
│ ---        ┆ ---          ┆ ---      ┆ ---      │
│ str        ┆ str          ┆ str      ┆ f64      │
╞════════════╪══════════════╪══════════╪══════════╡
│ 73862001   ┆ 73862001     ┆ IS_A     ┆ 0.0      │
│ 254502002  ┆ 254502002    ┆ IS_A     ┆ 0.0      │
│ 127337006  ┆ 127337006    ┆ IS_A     ┆ 0.0      │
│ 414403008  ┆ 414403008    ┆ IS_A     ┆ 0.0      │
│ 88425004   ┆ 88425004     ┆ IS_A     ┆ 0.0      │
│ …          ┆ …            ┆ …        ┆ …        │
│ 277387000  ┆ UNK          ┆ IS_A     ┆ null     │
│ 1296723006 ┆ UNK          ┆ IS_A     ┆ null     │
│ 10083006   ┆ UNK          ┆ IS_A     ┆ null     │
│ 1187499006 ┆ UNK          ┆ IS_A     ┆ null     │
│ 305543001  ┆ UNK          ┆ IS_A     ┆ null     │
└────────────┴──────────────┴──────────┴──────────┘